name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and Encryption code
        run: |
          pip install iac-inscript
          iac-inscript -i .
      - name: Publish
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.POETRY_HTTP_BASIC_PYPI_PASSWORD }}
        run: |
          cd dist/iac-init
          pwd
          keyring --disable
          pip install poetry
          poetry build
          poetry publish
